version: "3.8"
services:
    web:
        container_name: 'Gin_Gonic_Calculator'
        build:
            context: '.'
            dockerfile: 'Dockerfile'
        ports:
         - '8080:8080'
        networks:
         - gingonic-network
        volumes:
         - '.:/app'

networks:
    gingonic-network:
        driver: bridge